# This project configuration is the default file expected by the build system.
# Unless a different file is specified using the `CONF_FILE` CMake variable, you'll need to
# provide this file even if it is empty.

CONFIG_GPIO=y # Enable GPIO support, which is commonly used for controlling LEDs and reading button states.

CONFIG_PRINTK=y # Enable printk support for debugging output.