manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main              # ← PINNED version! make sure your sdk version matches 
      import: true                   # ← This pulls in all Zephyr's module deps

  self:
    path: zephyr_freestanding